#!/bin/tcsh
#
# Jeffrey Jose | 15 Jul, 2021

# Run as root (su). If you cant, make sure jeffjose is in `wheel` group
#   Fix that by `pw usermod jeffjose -G wheel`

#
#   $ pkg update
#   $ pkg install -y sudo
#
#   Add jeffjose to `sudo'ers`. First make sure, jeffjose is in `wheel` group
#   $ visudo # Uncomment the `%wheel ALL=(ALL) ALL` line

echo "If you cant become sudo, make sure you run "
echo " 1. su"
echo " 2. pkg update"
echo " 3. pkg install -y sudo"
echo " 4. Enable sudo for wheel group in visudo"

sudo pkg install -y git rust
