#!/bin/bash

# Setting up some directories
#
#

echo "--------------------------------"
echo "Setting up dotfiles in $HOME"
echo "--------------------------------"

mkdir -p $HOME/bin
mkdir -p $HOME/scripts
mkdir -p $HOME/Downloads
mkdir -p $HOME/.screen
mkdir -p $HOME/.config/nvim
mkdir -p $HOME/.config/espanso
mkdir -p $HOME/.config/containers
mkdir -p $HOME/.config/Code/User/
#mkdir -p $HOME/.config/catt/
#mkdir -p $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
mkdir -p $HOME/.ipython/profile_default/
mkdir -p $HOME/.screenlayout
mkdir -p $HOME/.jupyter/custom/

touch /tmp/cwdcmd_recent_dirs

# Ensure that the .aliases.sensitive.sh file exists
#
#
touch $HOME/.aliases.sensitive.sh

rm $HOME/bin/scrn
ln /usr/bin/screen $HOME/bin/scrn -s

# Link dotfiles
#
#
rm $HOME/.aliases
ln $HOME/dotfiles/.aliases $HOME/.aliases
rm $HOME/.aliases.bash
ln $HOME/dotfiles/.aliases.bash $HOME/.aliases.bash
rm $HOME/.colordiffrc
ln $HOME/dotfiles/.colordiffrc $HOME/.colordiffrc
rm $HOME/.cshrc
ln $HOME/dotfiles/.cshrc $HOME/.cshrc
rm $HOME/.cwdcmd
ln $HOME/dotfiles/.cwdcmd $HOME/.cwdcmd
rm $HOME/.gitconfig
ln $HOME/dotfiles/.gitconfig $HOME/.gitconfig
rm $HOME/.pdbrc
ln $HOME/dotfiles/.pdbrc $HOME/.pdbrc
rm $HOME/.precmd
ln $HOME/dotfiles/.precmd $HOME/.precmd
rm $HOME/.prompt
ln $HOME/dotfiles/.prompt $HOME/.prompt
rm $HOME/.screen/default
ln $HOME/dotfiles/.screen/default $HOME/.screen/default
rm $HOME/.screenrc
ln $HOME/dotfiles/.screenrc $HOME/.screenrc
rm $HOME/.tabletaliases
ln $HOME/dotfiles/.tabletaliases $HOME/.tabletaliases
rm $HOME/.vimrc
ln $HOME/dotfiles/.vimrc $HOME/.vimrc
rm $HOME/.XResources
ln $HOME/dotfiles/.XResources $HOME/.XResources
rm $HOME/.xmodmap
ln $HOME/dotfiles/.xmodmap $HOME/.xmodmap
rm $HOME/.xsession
ln $HOME/dotfiles/.xsession $HOME/.xsession
rm $HOME/.config/Code/User/keybindings.json
ln $HOME/dotfiles/keybindings.json $HOME/.config/Code/User/keybindings.json
#rm $HOME/.config/catt/catt.cfg
#ln $HOME/dotfiles/catt.cfg $HOME/.config/catt/catt.cfg
rm $HOME/.ipython/profile_default/ipython_config.py
ln $HOME/dotfiles/ipython_config.py $HOME/.ipython/profile_default/ipython_config.py
rm $HOME/.jupyter/custom/custom.js
ln $HOME/dotfiles/custom.js $HOME/.jupyter/custom/custom.js

rm $HOME/.config/nvim/init.vim
ln $HOME/dotfiles/init.vim $HOME/.config/nvim/init.vim

rm $HOME/.config/espanso/default.yml
ln $HOME/dotfiles/default.yml $HOME/.config/espanso/default.yml

rm $HOME/.config/containers/containers.conf
ln $HOME/dotfiles/containers.conf $HOME/.config/containers/containers.conf
