#!/bin/bash

usage() {
  echo "Usage: bootstrap-k3s [leader|minion] [name] [server-ip] [ip]"
  exit 1
}

bootstrapminion() {

  echo "[TASK] Installing k3s agent"
  k3sup join --server-ip $server_ip --ip $ip --user root
}

bootstrapleader() {

  echo "[TASK] Installing k3s server"
  k3sup install --ip $server_ip --user root

}

waitfor() {
  ping $1 | grep --line-buffered "bytes from" | head -1
}

preparehost() {

  cat _prepare-host.sh | lxc exec $name bash

  waitfor $ip && : || echo "Waiting for server to be up .."

  echo "[TASK] Copying ssh-key"
  sshpass -p kubeadmin ssh-copy-id -o StrictHostKeyChecking=no -f root@$ip >/dev/null 2>&1
}

case "$1" in
leader)
  echo -e ""
  echo -e "Setting up $2 ($3) ..."
  echo -e ""

  server_ip="$3"
  ip="$4"
  name="$2"

  preparehost
  bootstrapleader
  ;;
minion)
  echo -e ""
  echo -e "Joining $2 ($4) to $3 ..."
  echo -e ""

  server_ip="$3"
  ip="$4"
  name="$2"

  preparehost
  bootstrapminion
  ;;
*)
  usage
  ;;
esac
