#!/bin/bash
#
# Script strcutre based off of https://github.com/justmeandopensource/kubernetes
# Additional k3s specific info from  https://github.com/corneliusweig/kubernetes-lxd/blob/master/README-k3s.md

usage() {
  echo "Usage: k3s-lxc-setup [provision|destroy]"
  exit 1
}

NODES="kleader kminion1 kminion2"

kubeprovision() {
  # check if we have k8s profile or create one
  lxc profile list | grep -qo k8s || (lxc profile create k8s && cat k8s-profile-config | lxc profile edit k8s)
  echo
  for node in $NODES; do
    echo "==> Bringing up lxc - $node"
    lxc launch ubuntu:20.10 $node --profile k8s
    sleep 10
    echo "==> Setting up k3s"
    # TODO: Add string leader/minion and ip address
    ./_bootstrap-k3s $node
    echo
  done
}

kubedestroy() {
  for node in $NODES; do
    echo "==> Destroying $node..."
    lxc delete --force $node
  done
}

case "$1" in
provision)
  echo -e "\nProvisioning Kubernetes Cluster...\n"
  kubeprovision
  ;;
destroy)
  echo -e "\nDestroying Kubernetes Cluster...\n"
  kubedestroy
  ;;
*)
  usage
  ;;
esac
