- name: "LINUXBREW: Download linuxbrew Installer"
  get_url:
    url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
    dest: "/tmp/sh.linuxbrew-install.sh"
    mode: "0755"
    force: "yes"
  tags:
    - linuxbrew
    - brew

- name: "LINUXBREW: Install linuxbrew"
  command: "sh -c 'yes | /tmp/sh.linuxbrew-install.sh'"
  tags:
    - linuxbrew
    - brew
    - test
