- name: "YARN: Download yarn Installer"
  get_url:
    url: "https://yarnpkg.com/install.sh"
    dest: "/tmp/sh.yarnpkg-install.sh"
    mode: "0755"
    force: "yes"
  tags:
    - yarn

- name: "YARN: Install yarn"
  shell: /tmp/sh.yarnpkg-install.sh
  tags:
    - yarn

- name: "YARN: Install packages"
  community.general.yarn:
    name: "{{item}}"
    global: yes
    loop:
      - npm@latest
      - t-get
      - yarn-recursive
      - npx
      - coffeescript
      - less
      - firebase
      - firebase-tools
      - peerflix
      - gulp-cli

      # Typescript
      - typescript
      - ts-node

      # CLI Replacements
      - tldr

      # PostCSS
      - postcss-cli

      # astro
      - astro

      # scss
      - sass

      # degit
      - degit

      #jest
      - jest
