- name: "RUST/CARGO: Download Rust Installer"
  get_url:
    url: "https://sh.rustup.rs"
    dest: "/tmp/sh.rustup.rs"
    mode: "0755"
    force: "yes"
  tags:
    - rust
    - cargo

- name: "RUST/CARGO: Install rust/cargo"
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
    - cargo

- name: "RUST/CARGO: Install packages"
  community.general.cargo:
    name: "{{item}}"
  loop:
    # For gitstatus (prompt)
    - timeago-cli
    # For bumping versions
    - cargo-bump
    # For editing Cargo.toml files
    - cargo-edit
    # For doing background .rs file source check
    - bacon
    # git summary
    - onefetch
    # update installed binaries
    - cargo-update
    # rargs (https://github.com/lotabout/rargs)
    - rargs
    # find replacement
    - find-files
  tags:
    - rust
    - cargo
