- name: "VIM: Setup variables"
  set_fact:
    nvim_config_dir: "{{ansible_user_dir}}/.config/nvim"
    nvim_autoload_dir: "{{ansible_user_dir}}/.local/share/nvim/site/autoload"

- name: "VIM: Ensure neovim is present"
  become: yes
  apt:
    name:
      - neovim

- name: "VIM: Ensure .config directory exists"
  file:
    path: "{{nvim_config_dir}}"
    state: directory

- name: "VIM: Setup {init,plugins}.vim"
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: hard
  loop:
    - {
        src: "{{ansible_user_dir}}/dotfiles/nvim/init.vim",
        dest: "{{nvim_config_dir}}/init.vim"
      }
    - {
        src: "{{ansible_user_dir}}/dotfiles/nvim/plugins.vim",
        dest: "{{nvim_config_dir}}/plugins.vim"
      }

- name: "VIM: Create vim-plug target directory"
  file:
    path: "{{nvim_autoload_dir}}"
    state: directory
    mode: "0755"

- name: "VIM: Install vim-plug"
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{nvim_autoload_dir}}/plug.vim"

#- name: "VIM: Install plugins"
#  command:
#    cmd: "nvim -es -u {{ansible_user_dir}}/.config/nvim/init.vim +PlugInstall +qa"
#
