---
# tasks file for jeffjose
- name: Basic system tools
  become: true
  apt: 
    pkg: 
      - build-essential
      - curl
      - wget
      - sudo
      - tcsh
      - openssh-server
    state: latest
    update_cache: true
    
- name: git, gitk, git-gui
  become: true
  apt: 
    pkg: 
      - git
      - git-gui
      - gitk
    state: latest
    update_cache: true

- name: tools
  become: true
  apt: 
    pkg: 
      - neovim
      - tilix
      - ack
      - screen
      - ncdu
      - htop
      - gdebi
      - ffmpeg
      - vlc
      - gedit
      - gparted
      - tree
      - feh
      - youtube-dl
      - ntp
      - colordiff
      - d-feet
      - jq
      - npm
      - wavemon
      - nfs-common
      - nmap
      - hardinfo
      - mosh
      - golang
      - clang-format
      - snapd
      - detox
      - evince
      - neofetch
      - meld
    state: latest
    update_cache: true
