- name: "DESKTOP: Update packages"
  become: yes
  apt:
    update_cache: yes
    upgrade: "yes"
  tags:
    - apt

- name: "DESKTOP: Install gui packages"
  become: yes
  package:
    name:
      # Git
      - gitk
      - git-gui

      # Other
      - gpick
      - gedit
      - tilix
      - evince
      - meld
      - flameshot
      - vlc
      - gparted
      - feh

      # Torrents
      -  #qbittorrent
      - transmission

      # Fonts
      - fonts-firacode
      - fonts-inter
      - fonts-noto-color-emoji

      - ipython3
    state: latest
  tags:
    - apt
