---
- name: COMMON
  hosts: all
  tasks:
    - import_tasks: tasks/common/dotfiles.yml
    - import_tasks: tasks/common/essential-packages.yml
    - import_tasks: tasks/common/setup_user.yml
    - import_tasks: tasks/common/vim.yml
    - import_tasks: tasks/common/rust-cargo.yml
    - import_tasks: tasks/common/ssh-keygen.yml
  vars_files:
    - group_vars/all/secret.yml

- name: SERVER
  hosts: server
  tasks:
    - import_tasks: tasks/server/server-packages.yml
    - import_tasks: tasks/server/linuxbrew.yml
    - import_tasks: tasks/server/yarn.yml

- name: DESKTOP
  hosts: desktop
  tasks:
    - import_tasks: tasks/server/server-packages.yml
    - import_tasks: tasks/desktop/desktop-packages.yml
